### ISSUE TITLE
Idioma do Plone para PT-BR

### ISSUE THREAD

**Issue by acpj21** [CMCuritiba/extranet-cmc#51]
Definir o idioma padrão do Plone para Pt-br.

**Comment by acpj21** [comment]
Ao definir o idioma para português brasileiro, o backend "cai", com o seguinte log de erro:
`Volto is running in SEAMLESS mode
Proxying API requests from http://localhost:3000/++api++ to http://backend:8080/Plone
🎭 Volto started at 0.0.0.0:3000 🚀
RangeError: Incorrect locale information provided
    at Function.supportedLocalesOf (<anonymous>)
    at /app/node_modules/intl-locales-supported/dist/index.js:30:32
    at Array.every (<anonymous>)
    at Object.areIntlLocalesSupported [as default] (/app/node_modules/intl-locales-supported/dist/index.js:29:29)
    at createIntl (/app/node_modules/react-intl/dist/components/provider.js:65:42)
    at new IntlProvider (/app/node_modules/react-intl/dist/components/provider.js:88:19)
    at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
    at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
/app/node_modules/intl-locales-supported/dist/index.js:30
        return intlConstructor.supportedLocalesOf(locales).length === locales.length;
                               ^

RangeError: Incorrect locale information provided
    at Function.supportedLocalesOf (<anonymous>)
    at /app/node_modules/intl-locales-supported/dist/index.js:30:32
    at Array.every (<anonymous>)
    at Object.areIntlLocalesSupported [as default] (/app/node_modules/intl-locales-supported/dist/index.js:29:29)
    at createIntl (/app/node_modules/react-intl/dist/components/provider.js:65:42)
    at new IntlProvider (/app/node_modules/react-intl/dist/components/provider.js:88:19)
    at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
    at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
`

**Comment by acpj21** [comment]
[Usando o Volto em Português](https://github.com/plone/volto/issues/4644)
